# Generated by Django 2.1.2 on 2019-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathroom',
            field=models.IntegerField(),
        ),
    ]
