# Generated by Django 2.1.2 on 2019-09-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190908_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(choices=[('100000', '$100,000'), ('200000', '$200,000'), ('300000', '$300,000'), ('400000', '$400,000'), ('500000', '$500,000'), ('600000', '$600,000'), ('700000', '$700,000'), ('800000', '$800,000'), ('900000', '$900,000'), ('1000000', '$1M+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('AP', 'Andra Pradesh'), ('HYD', 'Hyderabad'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BH', 'Bihar'), ('P', 'Patna'), ('CHG', 'Chhattisgarh'), ('Rp', 'Raipur'), ('G', 'Goa'), ('GU', 'Gujarat'), ('H', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JAK', 'Jammu and Kashmir'), ('JK', 'Jharkhand'), ('RCH', 'Ranchi'), ('KR', 'Karnataka'), ('KRL', 'Kerala'), ('MP', 'Madya Pradesh'), ('BP', 'Bhopal'), ('MT', 'Maharashtra'), ('OD', 'Orissa')], max_length=20),
        ),
    ]
