# Generated by Django 2.1.2 on 2019-09-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20190908_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default=2, max_length=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='garages',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default=3, max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(choices=[('100000', '$100,000'), ('200000', '$200,000'), ('300000', '$300,000'), ('400000', '$400,000'), ('500000', '$500,000'), ('600000', '$600,000'), ('700000', '$700,000'), ('800000', '$800,000'), ('900000', '$900,000'), ('1000000', '$1M+')], max_length=3),
        ),
    ]
