# Generated by Django 2.1.2 on 2019-09-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190909_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.CharField(default='parking', max_length=30),
        ),
    ]
