# Generated by Django 2.1.2 on 2019-09-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='amenities',
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(to='listings.Amenities'),
        ),
    ]
