# Generated by Django 2.1.2 on 2019-09-09 20:26

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('listings', '0009_auto_20190909_2143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='Amenity',
        ),
    ]
