# Generated by Django 2.1.2 on 2019-09-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20190909_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floor_plan',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='video_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
