# Generated by Django 2.1.2 on 2019-09-23 10:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
    ]
