# Generated by Django 2.1.2 on 2019-09-09 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0010_auto_20190909_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 9, 22, 32, 13, 783966)),
        ),
    ]
