# Generated by Django 2.1.2 on 2019-09-11 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0014_auto_20190909_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 12, 1, 35, 42, 918908)),
        ),
    ]
