# Generated by Django 2.1.2 on 2019-09-15 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0016_auto_20190915_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 15, 12, 44, 36, 573366)),
        ),
    ]
