# Generated by Django 2.1.2 on 2019-09-22 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0021_auto_20190922_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 18, 28, 22, 26457)),
        ),
    ]
