# Generated by Django 2.1.2 on 2019-09-22 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0022_auto_20190922_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 23, 33, 42, 208079)),
        ),
    ]
