# Generated by Django 2.1.2 on 2019-09-23 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0023_auto_20190922_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 23, 12, 39, 21, 537005)),
        ),
    ]
