# Generated by Django 2.1.2 on 2019-09-23 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0024_auto_20190923_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 23, 14, 44, 18, 17009)),
        ),
    ]
